# Generated by Django 5.2.4 on 2025-07-20 16:07

import django.core.validators
import django.db.models.deletion
import phonenumber_field.modelfields
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('date_modified', models.DateTimeField(auto_now=True)),
                ('phone_number', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None)),
                ('country', models.CharField(max_length=200)),
                ('city', models.CharField(max_length=200)),
                ('zip_code', models.CharField(max_length=10, validators=[django.core.validators.RegexValidator(message='Enter a valid US zip code.', regex='^\\d{5}(-\\d{4})?$')])),
                ('address', models.CharField(max_length=200)),
                ('birth_date', models.DateField()),
                ('job_address', models.CharField(max_length=200)),
                ('job_type', models.CharField(max_length=200)),
                ('balance', models.IntegerField()),
                ('is_verified', models.BooleanField(default=False)),
                ('payment_image', models.ImageField(upload_to='customer/payment/')),
                ('iban', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
