# Generated by Django 5.2.4 on 2025-08-10 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0003_alter_customer_balance_alter_customer_birth_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='balance',
            field=models.IntegerField(default=0),
        ),
    ]
