# Generated by Django 5.2.4 on 2025-08-18 11:46

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0008_alter_customer_phone_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='trading',
            field=models.BooleanField(choices=[(True, ' + Positive'), (False, ' - Negative')], default=True),
        ),
        migrations.CreateModel(
            name='Bet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('summa', models.IntegerField()),
                ('open_date', models.DateTimeField(db_default=datetime.datetime(2025, 8, 18, 11, 46, 7, 906705, tzinfo=datetime.timezone.utc))),
                ('close_date', models.DateTimeField()),
                ('entry', models.IntegerField()),
                ('profit', models.IntegerField()),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='customer.customer')),
            ],
        ),
    ]
