# Generated by Django 5.2.4 on 2025-08-18 12:04

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0009_customer_trading_bet'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bet',
            name='open_date',
            field=models.DateTimeField(db_default=datetime.datetime(2025, 8, 18, 12, 4, 29, 653693, tzinfo=datetime.timezone.utc)),
        ),
    ]
