# Generated by Django 5.2.4 on 2025-08-23 07:18

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0011_bet_entry_currency_bet_profit_currency_bet_quotation_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bet',
            name='type',
            field=models.CharField(blank=True, choices=[('buy', 'BUY'), ('sell', 'SELL')], max_length=4, null=True),
        ),
        migrations.AlterField(
            model_name='bet',
            name='open_date',
            field=models.DateTimeField(db_default=datetime.datetime(2025, 8, 23, 7, 18, 26, 721638, tzinfo=datetime.timezone.utc)),
        ),
    ]
