# Generated by Django 5.2.4 on 2025-08-23 12:39

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0012_bet_type_alter_bet_open_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bet',
            name='entry_currency',
        ),
        migrations.RemoveField(
            model_name='bet',
            name='profit_currency',
        ),
        migrations.RemoveField(
            model_name='bet',
            name='summa_currency',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='balance_currency',
        ),
        migrations.AlterField(
            model_name='bet',
            name='entry',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='bet',
            name='open_date',
            field=models.DateTimeField(db_default=datetime.datetime(2025, 8, 23, 12, 39, 26, 2757, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='bet',
            name='profit',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='bet',
            name='summa',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='customer',
            name='balance',
            field=models.FloatField(default=0),
        ),
    ]
