# Generated by Django 5.2.4 on 2025-08-23 12:42

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0013_remove_bet_entry_currency_remove_bet_profit_currency_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bet',
            name='close_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='bet',
            name='open_date',
            field=models.DateTimeField(db_default=datetime.datetime(2025, 8, 23, 12, 42, 43, 721180, tzinfo=datetime.timezone.utc)),
        ),
    ]
