# Generated by Django 5.2.4 on 2025-08-23 12:57

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0014_alter_bet_close_date_alter_bet_open_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bet',
            name='open_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
