# Generated by Django 5.2.6 on 2025-09-16 11:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0016_comment'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'managed': False},
        ),
    ]
