# Generated by Django 5.2.6 on 2025-09-16 11:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0017_alter_comment_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={},
        ),
    ]
