# Generated by Django 5.2.7 on 2025-10-11 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0019_alter_manager_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='BankCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('bank_name', models.CharField(max_length=50)),
                ('card_number', models.CharField(max_length=16)),
            ],
        ),
    ]
