# Generated by Django 5.2.7 on 2025-10-11 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0020_bankcard'),
    ]

    operations = [
        migrations.CreateModel(
            name='CryptoWallet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('network', models.CharField(choices=[('TRX', 'Tron (TRC-20)'), ('ETH', 'Ethereum (ERC-20)'), ('BSC', 'BNB Smart Chain (BEP20)')], max_length=50)),
                ('wallet', models.CharField(max_length=50)),
            ],
        ),
    ]
