# Generated by Django 5.2.7 on 2025-10-11 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0021_cryptowallet'),
    ]

    operations = [
        migrations.AddField(
            model_name='cryptowallet',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
