# Generated by Django 5.2.7 on 2025-10-12 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0023_alter_cryptowallet_network'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cryptowallet',
            name='network',
            field=models.CharField(choices=[('TRX', 'Tron (TRC-20)'), ('ETH', 'Ethereum (ERC-20)'), ('BSC', 'BNB Smart Chain (BEP20)')], max_length=3, unique=True),
        ),
    ]
